### ISSUE TITLE
Allowed to configure runtime directory

### ISSUE THREAD

**Issue by Camork** [JaneWardSandy/eclipse-pde-partial-idea#110]
**Is your feature request related to a problem? Please describe.**
Curently, the runtime path is pointed to 'partial-runtime' which is hardcoded.  It would be convenient to allow switch between multi workspaces

**Describe the solution you'd like**
We could add a config field in the run configuration page.

**Comment by JaneWardSandy** [comment]
This adjustment will be released in v1.6.2, and Jetbrains has been pushed for review.

<img width="1152" alt="image" src="https://github.com/JaneWardSandy/eclipse-pde-partial-idea/assets/15345355/8417253b-5110-4716-ade0-3bb190cc65f3">

**Comment by Camork** [comment]
Thanks, done really fast.
