### ISSUE TITLE
Is this plugin stable?

### ISSUE THREAD

**Issue by wonsuc** [JaneWardSandy/eclipse-pde-partial-idea#118]
Can I launch Eclipse RCP on IntelliJ Idea via this plugin? 
Is v2.0 more stable than v1.x? 
I'm developing a TeamCenter Rich Client program and am unsure if it's appropriate for this use case.

**Comment by JaneWardSandy** [comment]
Yes, you can use this plug-in to develop the plug-in of Teamcenter RAC and run and debug it.

V2.0 is still under development to support Maven and Gradle, and the main function has not been completed yet, not even the semi-finished product. So at present, v1.x is a stable version.

**Comment by wonsuc** [comment]
That's great news for me. 
Thanks for making a good plugin!
