### ISSUE TITLE
Support jars.extra.classpath

### ISSUE THREAD

**Issue by lppedd** [JaneWardSandy/eclipse-pde-partial-idea#13]
Usage in Eclipse:

![image](https://user-images.githubusercontent.com/19871649/121045850-2560ac80-c7b6-11eb-9926-7412806e9efe.png)

Which writes the `build.properties` file.  
Example of such file:

```
source.. = src/
output.. = bin/
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               icons/,\
               lib/commons-io-2.4.jar
bin.excludes = icons/VRPG$APP.xcf,\
               icons/Thumbs.db,\
               icons/sample.gif
jars.extra.classpath = lib/lombok.jar

```

**Comment by lppedd** [comment]
Could you point out where the libraries scanning is done?
I'd like to do this myself and open a PR.

**Comment by JaneWardSandy** [comment]
> Could you point out where the libraries scanning is done?
> I'd like to do this myself and open a PR.

1. On project opened or user click resolve workspace, it will call `cn.varsa.idea.pde.partial.plugin.config.TargetDefinitionService#resolve` to read all target location's jar and directory bundle.
2. When target location resolve done, notify `cn.varsa.idea.pde.partial.plugin.config.BundleManagementService#resolve` to build and select bundle version, copy bundle-class-path, and cache bundle dependency tree(re-exported bundle for speed up in checking package accessibility)
3. When it was done, it will call `cn.varsa.idea.pde.partial.plugin.config.BundleManagementService#onFinished` to create project library, setting module and create module library.

Hope it could help for you.

**Comment by lppedd** [comment]
@JaneWardSandy I've read the source code which register libraries. If I'm not mistaked all the libraries are created through `ModuleHelper`, which works as a static utility class.

I was thinking, given that libraries can come from multiple places why not create an extension point and implement it for each place? We have:

- `MANIFEST.MF`: `Bundle-ClassPath` (compile)
- `build.properties`: `jars.extra.classpath` (compile-only)
- Target configuration (provided)

A Module service could be exposed as an extension point.
```
PdeLibraryResolver
  > ManifestLibraryResolver
  > BuildLibraryResolver
  > TargetLibraryResolver
```

Also, given that the Target libraries are **not all visibile**, they could be registered as syntethic using `AdditionalLibraryRootsProvider`, while the user should see in the UI only the `MANIFEST.MF` `Require-Bundle` ones.

What do you think about this?

**Comment by JaneWardSandy** [comment]
@lppedd 😂I was new to dev idea plugins less than 3 month, and heard this extension points now, may be I was seem `AdditionalLibraryRootsProvider` before but I don't know what it was used for.
I had tried to read the code for Gradle, but I can't find it, so I write this code to register libraries.

It sounds great, I will try to move `ModuleHelper` to `AdditionalLibraryRootsProvider`, but kept the difference dependency scope for each location, sometime I would like to run `main` method to test SWT/JFace GUI or something else.

**Comment by JaneWardSandy** [comment]
Issue will fix by add `PdeModuleCompileOnlyResolver.kt` and release in 1.2.0
