### ISSUE TITLE
Select latest version of a library if multiple are present

### ISSUE THREAD

**Issue by lppedd** [JaneWardSandy/eclipse-pde-partial-idea#14]
![image](https://user-images.githubusercontent.com/19871649/121051936-2eec1380-c7ba-11eb-81d1-ca746201beb6.png)

**Comment by JaneWardSandy** [comment]
Current it will always select first appearance jar as library, I will add and combo to check the rule for it, it can be first appearance or the newest version in same target location, or the newest version in all location.

**Comment by lppedd** [comment]
Just to expand a bit on this. In Eclipse I've defined my target as

![image](https://user-images.githubusercontent.com/19871649/121140085-bdec4080-c839-11eb-8e8e-994bb638d707.png)

As you can we have

`org.eclipse.emf.common` (2.12.0...) coming from SDPShared (IBM RDi)
`org.eclipse.emf.common` (2.22.0...) coming from `{eclipse_home}` (Eclipse 4.20)

![image](https://user-images.githubusercontent.com/19871649/121140234-e5430d80-c839-11eb-9f14-5c46ce05dfda.png)

In this case Eclipse automatically selected the `2.12.0` version.  
I have no idea if the custom configuration path can influence this.

![image](https://user-images.githubusercontent.com/19871649/121140682-6bf7ea80-c83a-11eb-8395-98d554f79fab.png)

**Comment by lppedd** [comment]
@JaneWardSandy just tried to create a new Target. Eclipse **always** insert `{eclipse_home}` before `SDPShared`.
Maybe there is some implicit rule? No idea

**Comment by lppedd** [comment]
Ok. Now I've remembered how I created the target months ago.
When you add locations, all the plugin are selected by default. I then grouped-by Location

![image](https://user-images.githubusercontent.com/19871649/121144388-3b19b480-c83e-11eb-8492-8211f57c6e86.png)

And de-selected all the `{eclipse_home}` plugins.

![image](https://user-images.githubusercontent.com/19871649/121144532-5be20a00-c83e-11eb-946d-7c56abdc3354.png)

**Comment by JaneWardSandy** [comment]
@lppedd You can remove location `{eclipse_home}` before add new location `SDPShared`, then you don't need to de-selected that location at all.

**Comment by lppedd** [comment]
@JaneWardSandy a bit off topic, but in reality I need the `{eclipse_home}` just because of some `*.source` plugins.  
Infact it's not entirely de-selected.

![image](https://user-images.githubusercontent.com/19871649/121145485-4c16f580-c83f-11eb-86bf-9ede76af8f56.png)

So, summarizing, the rules would be:
- enable all plugins found in locations
- enable the first, or newest, plugin (based on setting) found in the _same_ location

**Comment by JaneWardSandy** [comment]
@lppedd that's right, as I think it will be added a combo to switch this setting.
additional, I think we need a new setting for `*.source` rule, current it must be same version, I think it can be the same as plugin import rule. like, all source, same with imported bundle version, newest source version

**Comment by lppedd** [comment]
@JaneWardSandy mmh I think same `source` version is still the better option, because you could have misaligned `.class` and source files if you pick the newest of both. Or maybe I misunderstood what you meant

**Comment by JaneWardSandy** [comment]
@lppedd some time we dev for IBM or Teamcenter portal was based on Eclipse 3.8.xx, and we were hard to download the same version's source for it, so I think maybe we can provider an option to ignore the version mismatch.

Do you think it is necessary?

<img width="417" alt="image" src="https://user-images.githubusercontent.com/15345355/121150434-1d684180-c876-11eb-9b8a-19aa40fd346f.png">

**Comment by lppedd** [comment]
@JaneWardSandy I too had to hack a bit the `source` bundles (I had to edit the MANIFEST version manually and re-sign the JAR).
Yes, a setting's option could be the most optimal way to handle this

**Comment by lppedd** [comment]
@JaneWardSandy yeah you'd have to store all the infos.  
For now I think it's ok to not do that, but it can be a precious functionality.

**Comment by lppedd** [comment]
As a starting point I could try to at least offer a _Content_ tab that lists the plugin on-the-fly.

**Comment by JaneWardSandy** [comment]
@lppedd I remove this issue from 1.1.2, and add into 1.1.3
I think I can implement this function in 1.1.3, as you said, it was a precious functionality.

This is the implement of the function I imagined: 
Offer a _Content_ tab, it will calculate the plugins on-time, group plugins by bundle symbol name, select the plugins and source that will add into libraries.

In general, default check rule will be same as current rule, just provider a tab to change the check plugins.

**Comment by lppedd** [comment]
@JaneWardSandy sounds good to me.  
Are you going to store the selected plugins as a configuration XML file? Seems like the most straightforward way.

**Comment by JaneWardSandy** [comment]
@lppedd Yes, I will store it into xml, as IDEA provided way.

**Comment by JaneWardSandy** [comment]
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/15345355/121469614-62fc4a00-c9ef-11eb-89b2-500dbb53680b.png">

**Comment by JaneWardSandy** [comment]
Issue will fix and release in 1.1.3

**Comment by JaneWardSandy** [comment]
@lppedd Manually create two guava source jar, and set version to 30 and 20
<img width="685" alt="image" src="https://user-images.githubusercontent.com/15345355/121501146-889a4b00-ca11-11eb-9e3e-b633c6d38980.png">

Add version 30, and then 20
<img width="755" alt="image" src="https://user-images.githubusercontent.com/15345355/121501298-ad8ebe00-ca11-11eb-98f6-88117633cad7.png">

Switch to `Content` tab, click `Reload` or `Reload By Default Rule`
`Reload`: default select version from saved xml, or else with the same with `Reload By Default Rule`
`Reload By Default Rule`: first time read the jar version
Guava source was first time add, by locations order, here will be version 30
<img width="873" alt="image" src="https://user-images.githubusercontent.com/15345355/121502102-6ce37480-ca12-11eb-9ff4-a53d86f20fb4.png">

Now swap version 30 and 20 in `Target` tab, switch to `Content` tab, click `Reload` or `Reload By Default Rule`
now it will be version 20 (cause we haven't save, `Reload` and `Reload By Default Rule` was the same rule)
<img width="641" alt="image" src="https://user-images.githubusercontent.com/15345355/121502424-bfbd2c00-ca12-11eb-983d-afdb2da58dbc.png">
<img width="839" alt="image" src="https://user-images.githubusercontent.com/15345355/121502402-baf87800-ca12-11eb-9cec-3e2952b04902.png">

**Every time you change the `Target` location, like add, remove, swap location, or edit, `Content` tab will not refresh until you click `Reload` or `Reload By Default Rule`**

**Comment by lppedd** [comment]
@JaneWardSandy that's a good starting point! Nice work 🚀
