### ISSUE TITLE
Migrate libraries register from ModuleHelper to EP

### ISSUE THREAD

**Issue by JaneWardSandy** [JaneWardSandy/eclipse-pde-partial-idea#16]
@JaneWardSandy I've read the source code which register libraries. If I'm not mistaken all the libraries are created through `ModuleHelper`, which works as a static utility class.

I was thinking, given that libraries can come from multiple places why not create an extension point and implement it for each place? We have:

- `MANIFEST.MF`: `Bundle-ClassPath` (compile)
- `build.properties`: `jars.extra.classpath` (compile-only)
- Target configuration (provided)

A Module/Project service could be exposed as an extension point.
```
PdeProjectLibraryResolver (workspace level API)
  > TargetLibraryResolver

PdeModuleLibraryResolver (module/plugin level API)
  > ManifestLibraryResolver
  > BuildLibraryResolver
```

Project libraries are valid for all Modules, as in Eclipse.

![image](https://user-images.githubusercontent.com/19871649/121255899-44416a80-c8ac-11eb-9959-6fb3db5efa16.png)

Also, given that the Target libraries are **not all visibile**, they could be registered as syntethic using `AdditionalLibraryRootsProvider`, while the user should see in the UI only the `MANIFEST.MF` `Require-Bundle` ones.
<s>This way you could avoid the `PackageAccessibilityInspection` most probably.</s>

Extension points are perfect for both public and internal usage. Plus, defining an API makes introducing changes easier.
What do you think about this?

_Originally posted by @lppedd in https://github.com/JaneWardSandy/eclipse-pde-partial-idea/issues/13#issuecomment-856932317_

**Comment by lppedd** [comment]
Here it's better to have a complete overwiew of how things should work. EPs are cool but they're better used for specific things.  

So we must establish when the libraries must be registered:
 - startup
 - explicit user action

And we must establish the type of libraries that gets to be registered:
 - project libraries: Target Platform
 - module libraries: `build.properties` and `MANIFEST.MF` 

As I wrote yesterday, a good approach is splitting responsibilities.  
```
PdeProjectLibraryResolver (workspace level API)
  > TargetLibraryResolver

PdeModuleLibraryResolver (module/plugin level API)
  > ManifestLibraryResolver
  > BuildLibraryResolver
```

Such APIs can then be used during startup. For example

```kotlin
class PostStartupActivity : StartupActivity {
  override fun runActivity(project: Project) {
    val title = EclipsePDEPartialBundles.message("config.target.service.resolving")
    val task = object : Backgroundable(project, title) {
      override fun run(progressIndicator: ProgressIndicator) {
        // PdeProjectLibraryResolver(s)
        EP_NAME.getExtensions(project).forEach {
          it.resolve(progressIndicator)
        }
      }
    }

    task.cancelText = EclipsePDEPartialBundles.message("config.target.service.cancel")
    ProgressManager.getInstance().run(task)
  }
}
```

However every `PdeProjectLibraryResolver` and `PdeModuleLibraryResolver` should be used also from explicit user actions.  
For example, a user click on "Reload Target Platform".
```kotlin
val targetLibraryResolver = EP_NAME.findExtensionOrFail(TargetLibraryResolver::class.java, project)
targerLibraryResolver.resolve(indicator)
```

This seems a bit unnatural to me. It would be better something like a Project service.
```
val targerLibraryResolver = project.service<TargetLibraryResolver>()
targerLibraryResolver.resolve(indicator)
```
------------------------

And now we must think about the `PdeModuleLibraryResolver`s, which could be coded as

```
class ManifestLibraryResolver(private val module: Module) : PdeModuleLibraryResolver {
  ...
}
```

But where should we place our
```
EP_NAME.getExtensions(module)
```
? Are there listeners for Module load?

**Comment by lppedd** [comment]
Ultimately I'd say, let's not use `AdditionalLibraryRootsProvider` for now.  
Let's register the Target Platform plugins as project libraries, and MANIFEST and Build additions as Module libraries.

Hope this overwiew can be useful.

**Comment by JaneWardSandy** [comment]
What you said is very useful, but I haven't figured out how to plan this part of the function for the time being.
It may be placed in a longer-term goal, such as version 1.2.0 or version 2.0.0. At the same time, I also need to look at the development ideas of other IDEA plug-ins. I still know very little at present.

A very long time has passed. So far, I still don’t know much about the mechanisms that Eclipse and IDEA can provide, and I have never used too many functions, so that when I started writing this plug-in, I aimed to realize the function, and the scalability it is the work of future reconstruction.

Thank you for your suggestions, and for guiding and assisting me in improving this plugin.

**Comment by lppedd** [comment]
@JaneWardSandy yeah I think it's better to clea-up functionality now.
I had already started looking up how to implement this yesterday night, just to come up with some ideas.  
Something like this would be ideal. So that a third party can hook up on the variuos parts of the plugin.


![ep_services](https://user-images.githubusercontent.com/19871649/121315009-3ae5eb80-c908-11eb-8344-2fda912dc738.png)

**Comment by lppedd** [comment]
Is it ok if I try to implement this in a separate fork branch? I have a bit of time this weekend.

**Comment by JaneWardSandy** [comment]
Sorry to reply so late.
You can do as much as you want in the new branch, and I will make adjustments before the official release of these changes.
Before we work together to improve EPs, `IP2` will only be released as an experimental version, and will only be merged into a separate branch. When the function is perfect, it will be merged into the `main` branch and released.
So in the independent branch, do what you want, and finally merge into the `IP2` branch.

**Comment by lppedd** [comment]
@JaneWardSandy that's fine. I have already forked the repo. Will push to a branch taken from IP2.

**Comment by JaneWardSandy** [comment]
ER will done and release in version 1.2.0
