### ISSUE TITLE
Partial-CompileOnly dependencies are not indexed

### ISSUE THREAD

**Issue by lppedd** [JaneWardSandy/eclipse-pde-partial-idea#38]
Project's `.iml` file.
On the left the original situation, not working. On the right the edited situation, working.

![image](https://user-images.githubusercontent.com/19871649/126234716-5232ee38-366a-43c6-b5ce-54d341821174.png)

**Comment by JaneWardSandy** [comment]
I seems was find virtual file when module content roots call `findFileByRelativePath` return `file` file, we should add it into library root with `jar` file.
This issue will fix and release in 1.2.3
