### ISSUE TITLE
Error running 'Main': properties.getProperty("osgi.splashPath") must not be null

### ISSUE THREAD

**Issue by deepamin-intel** [JaneWardSandy/eclipse-pde-partial-idea#41]
I have set the Eclipse path using Settings -> Eclipse Target, I have configuration directory with config.ini it. config.ini contains osgi.splashPath as well.

**Comment by JaneWardSandy** [comment]
It seems can not found config.ini in `%target%/configuration/config.ini`, may be you are not specify location to parent folder of `plugins` folder if it was RCP application.

Such as
<img width="629" alt="image" src="https://user-images.githubusercontent.com/15345355/127423472-d0bd26e0-2a22-4471-b566-fd2e9f9b65be.png">
<img width="654" alt="image" src="https://user-images.githubusercontent.com/15345355/127423509-131a816e-6086-4339-9ed9-0a27eb1614cb.png">

**Comment by JaneWardSandy** [comment]
I will make it skip transform the properties if config.ini not existed.
and it will release in 1.2.3.1

**Comment by deepamin-intel** [comment]
I have added the parent folder as well, my directory structure is C:\users\<username>\eclipse\configuration\config.ini and I have added C:\users\<username>\eclipse to Eclipse Target setting, anything else I might be missing?

**Comment by JaneWardSandy** [comment]
maybe it had read the config.ini file correct, but was clear when product and application wasn't equal from file and run configuration.
in version 1.2.3.1 I had change the read action and mark property can be `null`

**Comment by deepamin-intel** [comment]
when will 1.2.3.1 be released?

**Comment by JaneWardSandy** [comment]
1.2.3.1 was pending JetBrains' review, maybe tomorrow will be public.
