### ISSUE TITLE
Invalid extension points/tags in plugin.xml

### ISSUE THREAD

**Issue by deepamin-intel** [JaneWardSandy/eclipse-pde-partial-idea#44]
Any idea why the extension points and all the plugin.xml tags are invalid in my setup? 
![image](https://user-images.githubusercontent.com/77679096/127855549-afcc8711-d92e-45da-829d-a166df8238d1.png)

**Comment by JaneWardSandy** [comment]
it seems your `org.eclipse.ui` jar or `org.eclipse.ui.source` jar not include `schema/menus.exsd` file, so we can not read the EP definition file and resolve its structure.

**Comment by deepamin-intel** [comment]
I'm using Eclipse Commiters 2021-06 version, I checked the org.eclipse.ui and indeed it doesn't have schema file, any other thing I can do for this?

**Comment by JaneWardSandy** [comment]
you can download it from web, or extract from other version's source jar, then put it into `org.eclipse.ui` jar

like this
<img width="558" alt="image" src="https://user-images.githubusercontent.com/15345355/127866658-3bceb2c1-2314-41c7-9d7e-1aa7cbe20932.png">

don't forget we had two jar need to modify, they are `org.eclipse.core.expressions` and `org.eclipse.ui`

**Comment by deepamin-intel** [comment]
the jar file you have is quite old 3.8 version from 2012, I have 3.119.0 from latest release and for previous 4-5 releases as well, all of which don't have the schemas, sure I can download and add to jar, but that would mean with every update I will have to change the jar file, wouldn't it be better to rely on something else for this schemas?

**Comment by JaneWardSandy** [comment]
If you are using eclipse not its product (like Teamcenter or IBM), you can download Eclipse SDK, it contains source jar, that was included source java and schema file.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/15345355/127867844-e6e09ebd-3eae-4b6c-aa41-e48c727dcd38.png">

**Comment by deepamin-intel** [comment]
I am using Eclipse as well, no product of it. I downloaded the SDK from https://archive.eclipse.org/eclipse/downloads/drops4/R-4.19-202103031800/ as it's the latest one, but still it's the same there are no schemas :(

**Comment by deepamin-intel** [comment]
I think I got the sources, will try out futher :)

**Comment by JaneWardSandy** [comment]
source jar should place in plugins directory.
you can use eclipse install software function to install SDK, it will automatic extract into eclipse/plugins directory
specify version or install the latest version SDK
> Latest Eclipse Release	http://download.eclipse.org/releases/latest

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/15345355/127870103-8e1a8385-2833-496d-8c54-c32b5ac2b9d6.png">


if you had already put source jar to location, don't forget `reload` location and  `reload content by default rule`
<img width="851" alt="image" src="https://user-images.githubusercontent.com/15345355/127870678-6feb0407-fe81-479a-9de0-ed1bb12d1dcf.png">

<img width="798" alt="image" src="https://user-images.githubusercontent.com/15345355/127870506-f87ff12f-415b-4f84-afe5-c498d2ed9de6.png">

**Comment by deepamin-intel** [comment]
yes, I have the org.eclipse.ui.source file in the plugins directory, which is added in the Eclipse Target, but still the Cotent tab only has ui plugin and not the source one, I reloaded as well. Invalidated cache and restarted the IDE as well, still it is not picking up the source jar

**Comment by deepamin-intel** [comment]
![image](https://user-images.githubusercontent.com/77679096/127871693-57c5256c-1d5b-478f-b2e6-a7e712d5921c.png)
![image](https://user-images.githubusercontent.com/77679096/127871838-7b4f0c6d-976f-4ede-913e-bc37a3e33f2c.png)
first one is the source jar in the directory I have added in Eclipse Target

**Comment by JaneWardSandy** [comment]
It seems was resolve and verify correctly.
<img width="814" alt="image" src="https://user-images.githubusercontent.com/15345355/127872105-593a6744-95de-40b3-ba8c-99c2fcc2fdb7.png">

could you take a picture in library like this below for me? and the sec picture like this [source schema](https://github.com/JaneWardSandy/eclipse-pde-partial-idea/issues/44#issuecomment-891019374), maybe I can try to find out why the schema was not load.
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/15345355/127872579-4134a78b-903e-4c1b-b064-f2934a288ddf.png">

**Comment by deepamin-intel** [comment]
![image](https://user-images.githubusercontent.com/77679096/127873768-ca31a0e0-5b0d-4d1d-8d5e-931ae9352ebd.png)

**Comment by JaneWardSandy** [comment]
This issue has been fixed, and will release in 1.3.0
Now it can load schema from `source` jar correctly.

<img width="738" alt="image" src="https://user-images.githubusercontent.com/15345355/128115916-3ed43d22-1ead-4c35-a168-f414065944b6.png">
