### ISSUE TITLE
Search box in Eclipse target's Content tab

### ISSUE THREAD

**Issue by deepamin-intel** [JaneWardSandy/eclipse-pde-partial-idea#45]
**Is your feature request related to a problem? Please describe.**
There are 3-4000 bundles and scrolling through everything is not scalable for finding one plugin

**Describe the solution you'd like**
A textbox on top of content tab which can be used to search the plugins in contents.

**Comment by JaneWardSandy** [comment]
I'd like had a function that can quickly search like IDEA project structure view, but I hadn't found how to implement it.
Maybe I can add a text field to spend this time

<img width="416" alt="image" src="https://user-images.githubusercontent.com/15345355/127873206-fc342fae-6bc2-4d64-ba68-6b159c6cdebc.png">

**Comment by deepamin-intel** [comment]
If I find which extension point project structure view uses for that search thing I will add it here.

**Comment by JaneWardSandy** [comment]
I had install a speed search handler on `table`/`list`/`combobox`, now you can quick search content.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/15345355/128119222-5114d443-286c-451e-b89e-599de30652f5.png">
<img width="717" alt="image" src="https://user-images.githubusercontent.com/15345355/128119239-b542d3ee-6ceb-47a0-984c-6380bf5129d6.png">
