### ISSUE TITLE
Wrong application name in run/debug configuration

### ISSUE THREAD

**Issue by deepamin-intel** [JaneWardSandy/eclipse-pde-partial-idea#46]
**Describe the bug**
The application name of the org.eclipse.ui.ide.workbench is somehow added as org.eclipse.ui.ide.application.org.eclipse.ui.ide.workbench and due to this it is not able to find the application in the registry. In the screenshot added in documentation correct application name can be seen. 

**Expected behavior**
 org.eclipse.ui.ide.workbench available in application name instead of org.eclipse.ui.ide.application.org.eclipse.ui.ide.workbench

**Screenshots**

**Which version of the library did you use?**
release version: 1.2.3.1

![image](https://user-images.githubusercontent.com/77679096/127898313-9668db4f-65e4-4280-a5e1-e4f88d9a5024.png)

**Comment by JaneWardSandy** [comment]
This issue has been fixed, and will be release in 1.3.0

<img width="654" alt="image" src="https://user-images.githubusercontent.com/15345355/128115798-463e4fb5-589d-46e6-be4b-f299ede4a843.png">
