### ISSUE TITLE
Bundle not found even when available in the Eclipse target

### ISSUE THREAD

**Issue by deepamin-intel** [JaneWardSandy/eclipse-pde-partial-idea#48]
**Describe the bug**
The bundles which are added in Eclipse target are not getting found at runtime, probably due to exact string with "v<timestamp>". The same version is available in the target but still it complains, this is happening for almost all of the modules.

**Expected behavior**
Version found in the required version range if available in target.

**Which version of the library did you use?**
release version: 1.3.0

![image](https://user-images.githubusercontent.com/77679096/128344586-9eaec95a-faf6-4911-a331-77ec2f14225b.png)

**Comment by JaneWardSandy** [comment]
Please confirm the file content in `%project%/out/partial-runtime/config/org.eclipse.equinox.simpleconfigurator/bundles.info`
Search the line start with `org.objectweb.asm,` and check witch version was used, it seems was using `8.0.1` but `[7.0.0, 7.1.0)` was required.
Eclipse default allow using multi versions bundle, and our plugin require one.

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/15345355/128448817-38da5090-5e59-4340-a879-1805d9398692.png">

**Comment by JaneWardSandy** [comment]
Now I'm working with re-impl `content` tab, let it allow use multi version. and all bundle identify must redesign, version and version range need to be consider too.

**Comment by deepamin-intel** [comment]
Yes, having multi version dependencies is something really useful, one of my project depends on com.google.guava > 27.0 and another one requires 21.0-22.0, I think the target should select the range of plugin version available in the plugins/target directory e.g. [21.0-30.0) like this.

**Comment by deepamin-intel** [comment]
Hi @JaneWardSandy, when is 1.3.1 planned to be released? 
If you need any help, I am open for contributions.

**Comment by JaneWardSandy** [comment]
1.3.1 version is planned to be released on the 15th of this month, it may be early.
There are a lot of places that need to be modified. The previous judgment and basis were limited to BSN, and now the version and version range need to be added.

**Comment by JaneWardSandy** [comment]
1.3.1 has been release, and waiting JetBrains' review and approval in order to be publicly available.

<img width="1011" alt="截屏2021-08-10 16 42 04" src="https://user-images.githubusercontent.com/15345355/128843506-1c9419ce-d440-4de2-8e7d-ba54272264f0.png">

**Comment by deepamin-intel** [comment]
Thanks a lot, Jane! 
I will try out the new release once it is available tomorrow.

**Comment by deepamin-intel** [comment]
I tried the release version 1.3.1 as it was available today, there is a performance issue with new release while resolving the target definition,
![image](https://user-images.githubusercontent.com/77679096/128867355-b8a0323a-5718-4556-a710-2dc5c237529f.png)
After this my IDE froze and I had to close it forcefully

**Comment by deepamin-intel** [comment]
I have a 128 gb ram with i9 system and still this is too much. 
![image](https://user-images.githubusercontent.com/77679096/128868120-7bc0f8e7-44fb-4f4a-8216-e7edbaa3af5f.png)

**Comment by JaneWardSandy** [comment]
How many heap size you were assign for IDEA?
From your figure, it seem less than 2GB, IDEA indexing will use many RAM, it would be better to allocate more memory.

I usually import 1.3k bundles, it will take 2GB at least, and it is estimated that about 800MB is used to store resolving and indexing content.

Maybe it will get better if you allocate more memory.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/15345355/128871929-7588e199-d12a-457f-89dc-20958db9a1d0.png">
<img width="860" alt="image" src="https://user-images.githubusercontent.com/15345355/128871990-ca8dbf8f-0349-4a15-8003-6ac1ef354c05.png">
<img width="521" alt="image" src="https://user-images.githubusercontent.com/15345355/128872068-22b441d5-d791-4036-83c4-b9f92bcc90e4.png">
<img width="868" alt="image" src="https://user-images.githubusercontent.com/15345355/128872097-bf5b6eae-a12d-49e3-9d01-e7bf9cc43f1d.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/15345355/128872177-5cb9e99a-295f-4734-bcff-611f11d52641.png">

**Comment by deepamin-intel** [comment]
I increased it to 4GB but still the performance is not great, it takes long time and the UI is freezing time to time

**Comment by deepamin-intel** [comment]
Still the plugins are not being found when they are available in the target version range 
![image](https://user-images.githubusercontent.com/77679096/128877848-ac34f45f-fcc7-4206-98d2-0acd5262a096.png)
Should I reopen the issue?

**Comment by JaneWardSandy** [comment]
When UI freezing, IDEA will create `threadDumps-freeze` directory in log directory, and it will log `WARN - .diagnostic.PerformanceWatcher - UI was frozen for 5750ms, details saved to` to log file, we can read this log file and detail file to try analysis the problem.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/15345355/128878825-f0ea1d44-bcf7-4a76-b1c6-dd8beeb113fa.png">
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/15345355/128879868-778bff2a-2d08-4b45-b4cf-643d06802790.png">

**Comment by JaneWardSandy** [comment]
I can not duplicate the issue which was `org.eclipse.jface` not found.
Which version of `eclipse` SDK was use to import? I want to download the same `eclipse` to reappear question.

Additionally, could you upload the content of file in `out/partial-runtime/config/org.eclipse.equinox.simpleconfigurator/bundles.info`? Launch eclipse target will read this file to resolve which plugin, version, location can be used for RCP.

**Comment by deepamin-intel** [comment]
I'm using latest Eclipse SDK from here https://download.eclipse.org/eclipse/downloads/drops4/R-4.20-202106111600/

**Comment by JaneWardSandy** [comment]
BTW, Does `Invalidate Caches...` operation alleviate UI freezing?

<img width="272" alt="image" src="https://user-images.githubusercontent.com/15345355/128882407-14626366-d111-4225-bda8-e8327ffbcae5.png">

<img width="430" alt="image" src="https://user-images.githubusercontent.com/15345355/128882206-84629fb3-328c-4c8d-8ac4-34c3ebc6a8e5.png">

**Comment by deepamin-intel** [comment]
[logs.zip](https://github.com/JaneWardSandy/eclipse-pde-partial-idea/files/6962370/logs.zip)
I have added the config.ini and bundles.info in this zip file

**Comment by deepamin-intel** [comment]
After Invalidate Caches... and restart it tries to rebuild the target def and updates indexes again so yes, it takes some time for the IDE to be fully responsive.

**Comment by JaneWardSandy** [comment]
Emm... I cannot duplicate this issue on my machine
maybe you can try to:
- delete directory `partial-runtime` under `out` directory to clean run config cache
- use run configuration `Eclipse Application Remote Partial`, launch RCP by using `wishes launcher`, that will load all plugins in locations

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/15345355/128972732-df05c48f-63e1-45d6-90ae-80a966640c4e.png">

**Comment by JaneWardSandy** [comment]
I saw you were add `.p2` and `eclipse rcp` into `eclipse target` at the same time.
delete `.p2` from `eclipse target`, eclipse use `oomph` to manager which plugin will be able load when eclipse start, but we not. we will ask eclipse load all plugins in `eclipse target`, that will make eclipse conflict plugins.

stay `eclipse target` clean, just one `eclipse rcp` that you're writing plugins for, others was additional bundle that will put into RCP plugins too.

**Comment by deepamin-intel** [comment]
I have the eclipse.exe in eclipse location and all the required plugins are in .p2 so I am adding both the locations.
Can we have some logic where we can select the eclipse.exe manually and then I will only have to add .p2 location and not the eclipse one, as right now when I add the eclipse.exe location it automatically adds all the plugins in that directory

**Comment by JaneWardSandy** [comment]
`.p2` were include all plugins you were download and use before, event you not need it anymore, and `.p2` also include other eclipse rcp plugins too, not only for one eclipse.

**Comment by JaneWardSandy** [comment]
If you use `eclipse SDK` from eclipse not `eclipse installer`, all plugins will put into plugins directory not .p2

**Comment by deepamin-intel** [comment]
I need some plugins which are not in Eclipse SDK, anyway I made a separate directory to store those plugins so other plugins don't conflict, but still the issue is same.
![image](https://user-images.githubusercontent.com/77679096/129011221-c8010dd6-1425-455a-a89f-420f89e56c30.png)

**Comment by JaneWardSandy** [comment]
Did you delete 'runtime-partial'? Sometime we need to delete those file and let eclipse re-generate it to clear some strange question.

I haven't fully figured out the debugging method of eclipse, I just imitate the way that eclipse starts the new eclipse RCP to reimplement.

**Comment by deepamin-intel** [comment]
Yes, I deleted the runtime directory. I tried with Eclipse SDK directory in target and the Eclipse starts now however I still have some transitive dependency issue where some plugin depends on older version of other plugin which is not available in the target def and then it fails with exception. Eclipse automatically resolves those transitive dependencies I believe, would it be possible to have similar behavior in plugin?

**Comment by deepamin-intel** [comment]
I resolved the dependencies manually and I can run/debug fine. Process of resolving the dependencies is tedious though.

**Comment by JaneWardSandy** [comment]
I think this is possible. I will try to provide a window for checking and resolving dependencies in 'content' tab.

**Comment by JaneWardSandy** [comment]
Now we have a dialog to check dependencies, can be auto resolve will be able checked, gray row was cannot found related bundle.

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/15345355/129160574-74b7e266-b555-4d39-9a09-fd0abe2b9beb.png">

**Comment by JaneWardSandy** [comment]
Pre-release 1.3.1.2 can be download in GitHub release now.

**Comment by deepamin-intel** [comment]
Tried the Validate feature and it seems to be working perfect, however the manual dependency resolution is still an issue, we need to have some automated way of fetching the plugins from some link/p2 repo.

**Comment by JaneWardSandy** [comment]
So, until 1.3.1.2, this issue was fixed.
Auto pickup plugins from `.p2` will impl with #54
