### ISSUE TITLE
UI Freezing on resolving bundles

### ISSUE THREAD

**Issue by JaneWardSandy** [JaneWardSandy/eclipse-pde-partial-idea#51]
I tried the release version 1.3.1 as it was available today, there is a performance issue with new release while resolving the target definition,
![image](https://user-images.githubusercontent.com/77679096/128867355-b8a0323a-5718-4556-a710-2dc5c237529f.png)
After this my IDE froze and I had to close it forcefully

_Originally posted by @deepamin-intel in https://github.com/JaneWardSandy/eclipse-pde-partial-idea/issues/48#issuecomment-895989720_

**Comment by JaneWardSandy** [comment]
> When UI freezing, IDEA will create `threadDumps-freeze` directory in log directory, and it will log `WARN - .diagnostic.PerformanceWatcher - UI was frozen for 5750ms, details saved to` to log file, we can read this log file and detail file to try analysis the problem.
> 
> <img alt="image" width="462" src="https://user-images.githubusercontent.com/15345355/128878825-f0ea1d44-bcf7-4a76-b1c6-dd8beeb113fa.png">
> 
> <img alt="image" width="1023" src="https://user-images.githubusercontent.com/15345355/128879868-778bff2a-2d08-4b45-b4cf-643d06802790.png">

**Comment by JaneWardSandy** [comment]
> BTW, Does `Invalidate Caches...` operation alleviate UI freezing?
> 
> <img alt="image" width="272" src="https://user-images.githubusercontent.com/15345355/128882407-14626366-d111-4225-bda8-e8327ffbcae5.png">
> 
> <img alt="image" width="430" src="https://user-images.githubusercontent.com/15345355/128882206-84629fb3-328c-4c8d-8ac4-34c3ebc6a8e5.png">

**Comment by JaneWardSandy** [comment]
> [logs.zip](https://github.com/JaneWardSandy/eclipse-pde-partial-idea/files/6962370/logs.zip)
> I have added the config.ini and bundles.info in this zip file

**Comment by JaneWardSandy** [comment]
> After Invalidate Caches... and restart it tries to rebuild the target def and updates indexes again so yes, it takes some time for the IDE to be fully responsive.

**Comment by JaneWardSandy** [comment]
@deepamin-intel UI freezing report here

**Comment by deepamin-intel** [comment]
[threadDump-20210810-151500.txt](https://github.com/JaneWardSandy/eclipse-pde-partial-idea/files/6962550/threadDump-20210810-151500.txt)
I have many folders for threadDump in the logs dir, I have added one of the longest ones (66 sec)

**Comment by JaneWardSandy** [comment]
Thx, I will read the file and try to find the reason of hang of EDT or AWT thread

**Comment by JaneWardSandy** [comment]
From `threadDump` file, I found it was waiting EDT in method `applicationInvokeAndWait`, and it was waiting library commit, in deep reason was waiting `index` update library, it rebuild `ObjectOpenHashSet` hash with capacity.

Current I don't have any idea to resolve this issue, expanding memory allocation may temporarily suppress this problem.

<img width="955" alt="image" src="https://user-images.githubusercontent.com/15345355/128960282-570ff087-11b2-4bce-8bcc-367560010c47.png">
<img width="734" alt="image" src="https://user-images.githubusercontent.com/15345355/128960371-f5a1c366-6ca8-407d-b8d9-4ee0c6c2bfdc.png">

**Comment by deepamin-intel** [comment]
I think the commit method in IntelliJ code should be fine as other plugins must be using it and the code should be thoroughly tested. I was going through the patch you made for multi version bundles and I think the plugin is caching/storing too much of data resulting in low memory on IDE and ergo freeze on UI. I think the caching needs to be smart like only cache the latest version of plugin and then the older ones should be on demand, one more thing which can be done is supporting .targetdefinition files like Eclipse, where the target only loads the plugins which are required by that project.

**Comment by JaneWardSandy** [comment]
By using memory analysis, bundle caching use less than 0.1% heap size, over 48.3% were use by `byte[]`, `String`, `Object[]`, they are create and catch by `indexes` system.

lot of memory use cause we put too many jar into library, and IDEA index those jar will use lot of memory.
maybe you can add some bundle to `eclipse target` only you need, don't add all to it. that will let you use lower memory to coding.

I think I will not change the setting to load the plugins that was required by project or .targetdefinition.
 cause eclipse was do with this, and until you add `import-package` or `required-bundle`, you won't be able to use class or event don't know we have that class in some plugin.

**Comment by lppedd** [comment]
@JaneWardSandy are you both saying there has been a sudden degradation of performance in the latest release?

**Comment by lppedd** [comment]
I'm testing the plugin with about 600 bundles. 8GB of Xmx are more then sufficient and the UI does not freeze.
If there is an issue it is most probably related to the indexing mechanism of IDEA.

@deepamin-intel my suggestion would be to export shared indexes, if the target does not change often (or never changes).
See https://www.jetbrains.com/help/idea/shared-indexes.html#project-shared-indexes

**Comment by JaneWardSandy** [comment]
@lppedd yes, I think it was low memory which indexing, I had test it with 1.3k+ bundles, 4GB of Mmx was fine. first time indexing will slow, but after now, open the same project without change target, it will speed up with stored indexes.
So I think this issue was not a problem if we can assign more memory for IDEA.
