### ISSUE TITLE
Eclipse target from eclipse that using oomph, but can not read plugins from .p2 repo

### ISSUE THREAD

**Issue by JaneWardSandy** [JaneWardSandy/eclipse-pde-partial-idea#54]
Tried the Validate feature and it seems to be working perfect, however the manual dependency resolution is still an issue, we need to have some automated way of fetching the plugins from some link/p2 repo.

_Originally posted by @deepamin-intel in https://github.com/JaneWardSandy/eclipse-pde-partial-idea/issues/48#issuecomment-897478346_

**Comment by JaneWardSandy** [comment]
@deepamin-intel Although I don't like oomph very much, I did encounter the situation that I had to use oomph when I was using the Windows system, so I could only get the plug-in from the .p2 repository.  
So I will try to achieve the function of getting eclipse instance related plug-ins from the .p2 repository. There must be a file to record which plug-ins the current eclipse instance is associated with.

But still, we will not achieve that function which was related by `RCP`, `e4`, `product`, `feature`, `fragment`, and so on, all of `PDE partial` was `plugins` function. 
We want a better plug-in development environment, not a large and complete re-implementation of Eclipse.

**Comment by deepamin-intel** [comment]
yes, sure I get that we don't want complete re-implementation of Eclipse (even I am not a great fan of it :P) but still auto dependency resolution is something nice to have.

**Comment by JaneWardSandy** [comment]
@deepamin-intel we now support provider bundles from `Eclipse Oomph (.p2 repo)`, `Eclipse SDK`, `Directory`, and provider move to EPs for extension support.

This feature has been release in 1.3.2, now it was pending approve by JetBrains.

<img width="734" alt="截屏2021-08-14 12 53 05" src="https://user-images.githubusercontent.com/15345355/129434995-4f7436c6-4558-428d-b9b0-aad3800baafd.png">
<img width="664" alt="截屏2021-08-14 12 53 24" src="https://user-images.githubusercontent.com/15345355/129434998-514d348b-d49a-4629-881a-b459022deb0a.png">
<img width="1069" alt="截屏2021-08-14 12 52 42" src="https://user-images.githubusercontent.com/15345355/129435005-d016c3ea-37bb-486e-8772-c15985110145.png">
