### ISSUE TITLE
What is this Plugin Exactly?

### ISSUE THREAD

**Issue by NicolasRodriguez676** [JaneWardSandy/eclipse-pde-partial-idea#63]
Can I use this plugin to target embedded devices (using CLion) that I would otherwise would have to use Eclipse?

**Comment by JaneWardSandy** [comment]
Sorry it can't.

This plugin just a part of [`Plug-in Development Environment`](https://www.eclipse.org/pde/) of Eclipse, with `OSGI` and language of `JVM` to build a plug-ins for RCP/RAP products.

**Comment by NicolasRodriguez676** [comment]
Thanks
