### ISSUE TITLE
Eclipse executable shouldn't be necessary

### ISSUE THREAD

**Issue by hengsin** [JaneWardSandy/eclipse-pde-partial-idea#68]
**Describe the bug**
The local application launcher require the presence of the Eclipse executable in addition to the Eclipse launcher jar.

**Expected behavior**
Should work like the IntelliJ Jar application launcher where only the Eclipse Launcher jar is needed.

**Comment by JaneWardSandy** [comment]
On Eclipse, it's command include launcher and name, I haven't tested what unknown problems will occur when these two parameters are not provided, so I use Eclipse's parameters to provide this parameter.
If it is confirmed that there is no effect in subsequent tests, I will remove this required parameter.

<img width="830" alt="image" src="https://user-images.githubusercontent.com/15345355/154787766-109d2afe-c7a2-4d2e-b4df-d8cff978d022.png">

**Comment by hengsin** [comment]
Perhaps you can make it optional ? Right now, the extension throws NPE if the launcer executable is missing. I'm not sure about RCP but we are doing server side Eclipse application (i.e using osgi/equinox, p2 and jetty) and doesn't need the launcher part.

**Comment by JaneWardSandy** [comment]
Issue will be fix and release in 1.3.6
