### ISSUE TITLE
Inter module dependency not working for packages re-exported through embedded jar

### ISSUE THREAD

**Issue by hengsin** [JaneWardSandy/eclipse-pde-partial-idea#73]
**Describe the bug**
Build not working. Have to manually fix it by adding the embedded jar to Project Structure > Libraries.

**To Reproduce**
1. Module 1 added Jar 1 to its Runtime Classpath (Bundle-ClassPath)
2. Module 1 re-export packages from Jar 1 (Export-Package)
3. Module 2 import the re-exported packages from Jar 1 (Import-Package)
4. See build error

**Expected behavior**
Auto add the embedded jar to Project Structure > Libraries ?

**Comment by JaneWardSandy** [comment]
Still using `test` project,

1. Copy `guava` jar into `lib` directory under `module1`
2. Modify `manifest.mf` of `module1` to add exported package  `com.google.common.collect`, and add `guava` jar to `Bundle-ClassPath`
3. Resolve the manifestof `module1` or workspace
4. `guava` jar should be add into `Partial-Runtime` library of `module1` automatic
5. Modify `manifest.mf` of `module2` to add import package `com.google.common.collect`
6. Resolve the manifest of `module2` or workspace
7. Using `Sets.newHashSet("A")` in Class of `module2`, it should not be have a warning.

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/15345355/155249570-c2b27451-d047-4d92-8c03-cd08aa9cd21e.png">

**Comment by hengsin** [comment]
Test with 1.3.6.4, this is not working as describe above. I've try both Import-Package and Require-Bundle, neither work.

**Comment by JaneWardSandy** [comment]
> Test with 1.3.6.4, this is not working as describe above. I've try both Import-Package and Require-Bundle, neither work.

Could you please attach the demo project?

**Comment by hengsin** [comment]
[test2.zip](https://github.com/JaneWardSandy/eclipse-pde-partial-idea/files/8202499/test2.zip)

After more testing, found out that it is working fine with non Maven project but fall apart with Maven project.

**Comment by JaneWardSandy** [comment]
> [test2.zip](https://github.com/JaneWardSandy/eclipse-pde-partial-idea/files/8202499/test2.zip)
> 
> After more testing, found out that it is working fine with non Maven project but fall apart with Maven project.

As we known, `Maven` will maintain the dependencies when you click `refresh`, it will remove all dependency entry that not under `Maven dependency tag`.

This plugins will add dependency entry programmatically, and on `Maven`/`Gradle` project, IDEA will alert those dependency entry will lost after `Maven`/`Gradle` refresh the dependency.

So, it was not a bug as what I said in [comparison](https://github.com/JaneWardSandy/eclipse-pde-partial-idea#comparison) section. This plugins has no plant to comparison with `Maven`/`Gradle` yet.

**Comment by JaneWardSandy** [comment]
If you feel this compatibility is a must, I would be very grateful if you could help write the relevant code and submit a PR.
