### ISSUE TITLE
Default compiler output to target, target/classes and target/test for Maven project

### ISSUE THREAD

**Issue by hengsin** [JaneWardSandy/eclipse-pde-partial-idea#76]
**Is your feature request related to a problem? Please describe.**
The default output directory for Maven project is target, target/classes and target/test. However, the Eclipse-Partial facet default to out/production for all type of project, Maven included.

**Describe the solution you'd like**
Use Maven default for Maven project

**Comment by JaneWardSandy** [comment]
This plugins not comparison with `Maven`/`Gradle` yet. And has no plant to comparison with `Maven`/`Gradle` nearly.

Now, it has an config to change the output path for current module, not for global or default value.

If you feel this compatibility is a must, I would be very grateful if you could help write the relevant code and submit a PR.
