### ISSUE TITLE
Automatically attach source bundles, if any found

### ISSUE THREAD

**Issue by lppedd** [JaneWardSandy/eclipse-pde-partial-idea#77]
Currently sources have to be attached manually, as per screenshot.

![image](https://user-images.githubusercontent.com/19871649/163336165-ad2aaed1-4af1-4d5e-839a-5b12f5831c54.png)

When "Attach" is pressed, sources are displayed immediately, which means the platform know where to find them.
To improve usability sources could be attached automatically while resolving bundles.
This means documentation is available without further interactions.

_Btw, this plugin is a lifesaver_.

**Comment by JaneWardSandy** [comment]
Current we support attach source bundle automatically, even it was under different directory.

We add two bundle in two directory, `com.sun.el` and `com.sun.el.source`, both was OSGI bundle.
<img width="982" alt="image" src="https://user-images.githubusercontent.com/15345355/163345385-c51a0f7b-ed21-4af1-ab0b-b6e6091e86f4.png">

When resolving bundle, we will read the `Eclipse-SourceBundle` header to identify the host bundle, then pair then in content tab. If source bundle version was match the host bundle version, it will be selected by default, other it will select manually.
<img width="868" alt="image" src="https://user-images.githubusercontent.com/15345355/163345867-c2e63430-29c3-456f-bd6e-0c8798a66da8.png">
<img width="858" alt="image" src="https://user-images.githubusercontent.com/15345355/163347429-6c392bab-4714-404f-bda9-faf592b7e6d5.png">
<img width="982" alt="image" src="https://user-images.githubusercontent.com/15345355/163347144-a0ddd7d2-2b45-4525-a369-7bbe1b38bb07.png">

After change the source bundle attachment, and click `apply` or `OK`, it will change the library, add jar and source jar into it.
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/15345355/163347584-25adb8a6-42a8-4251-964a-4cbd3c370df3.png">
<img width="807" alt="image" src="https://user-images.githubusercontent.com/15345355/163347760-0f2535f5-6a51-43c3-a9d2-7fd7e1b25331.png">


Hope it can help.

**Comment by lppedd** [comment]
Got it, thanks! Testing with a separate source bundle works nicely.  
After investigating a bit I've found that sources are bundled in the same plugin with .class files

![image](https://user-images.githubusercontent.com/19871649/163355028-c8ba169b-ebb3-490a-9145-34e1a81883e2.png)

I think that's why it doesn't automatically attach them.

**Comment by lppedd** [comment]
If you think this case is not worth supporting, you're free to close the issue 😄
