### ISSUE TITLE
Question on how to setup a project.

### ISSUE THREAD

**Issue by renis1235** [JaneWardSandy/eclipse-pde-partial-idea#78]
Hello and thank you so much for bringing such a plugin to IntelliJ.

I have a question (or several). There is a project which is a mix of E4 (RCP) JavaFX and OSGi that I would like to run with Intellij and also configure everything as in Eclipse. 

I would love to do this with your plugin, but my knowledge on RCP apps is very limited, can you please provide a small tutorial step by step on how to import projects? 
I have tried it and until now I haven't been sucessful.

Thank you once again and I look forward to your answer.

Best regards

**Comment by renis1235** [comment]
Thank you for your quick reply.

I look forward to your answer/solution. :)

**Comment by JaneWardSandy** [comment]
@renis1235 the first version of [Quick start](https://github.com/JaneWardSandy/eclipse-pde-partial-idea/wiki/Quick-start) has been completed, hope to help you.

**Comment by renis1235** [comment]
@JaneWardSandy Thank you so much for taking the time to write it. I will check it out and be back with comments if there are any.
