### ISSUE TITLE
Provide a category/feature-based way of importing target platform artifacts

### ISSUE THREAD

**Issue by lppedd** [JaneWardSandy/eclipse-pde-partial-idea#80]
As per screenshot (do not worry about the remote repo, in IntelliJ I'm using the same but offline)

![image](https://user-images.githubusercontent.com/19871649/176438896-52831b8d-18cd-4dd3-a961-3d5d492d4eb6.png)

Currently there is no way to select specific features only, as in Eclipse.

![image](https://user-images.githubusercontent.com/19871649/176439240-3a5f1840-3a7e-40d6-976f-8eabc1e19964.png)

**Comment by JaneWardSandy** [comment]
Insert `feature` row level under `location`

<img width="982" alt="image" src="https://user-images.githubusercontent.com/15345355/176986494-a8463836-0d63-46c0-bc0d-3b701fed6170.png">

**Comment by lppedd** [comment]
@JaneWardSandy thanks for the quick implementation! Awesome.

**Comment by lppedd** [comment]
Seems like for my case it is not behaving correctly. Or maybe the p2 repository isn't correctly setup.

If you want to try it out, you can use
https://public.dhe.ibm.com/ibmdl/export/pub/software/htp/zos/tools/aqua3.2/direct/aqua3.2_all_update_site.zip

Things you'll notice:
1. You cannot pick the main directory, as 0 bundles are resolved. So you have to pick every internal `update.site` folder
2. Everything is under `Non-featured`

![image](https://user-images.githubusercontent.com/19871649/177136091-9e3b328e-d4e1-43c2-b96c-d140390e9065.png)

**Comment by JaneWardSandy** [comment]
I can't open the url, it's there any other way to download this zip file?
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/15345355/177136976-c89ba10a-a69d-4778-8cc6-24003571c64c.png">

**Comment by lppedd** [comment]
@JaneWardSandy does this link work?
https://ibm.github.io/mainframe-downloads/eclipse-tools.html

You can then pick IBM Explorer for z/OS.

**Comment by JaneWardSandy** [comment]
@lppedd I can open this page, but the final download link still alert 500 error

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/15345355/177138127-9cb3e20f-f544-4512-910d-e267fbdc628c.png">

**Comment by lppedd** [comment]
@JaneWardSandy the "entire p2 repository" one?

**Comment by JaneWardSandy** [comment]
@lppedd Both `Entire p2 repository` and `Individual p2 zip files`

**Comment by lppedd** [comment]
@JaneWardSandy this is totally public so it is strange. What I'll do if it doesn't work in a new "incognito" window, is download it and send you a link via mail (e.g. mega.io), if it's ok. Let me know.

**Comment by JaneWardSandy** [comment]
@lppedd `incognito` window, safari, chrome, or using VPN connect to U.S., JP, or using window with virtual machine, not work anyway.

Please send it to me by mail (I can open mega.io).

**Comment by JaneWardSandy** [comment]
@lppedd Problem resolved, last version I just read the feature bundle as directory, but P2 repository's feature bundle was jar file, this occurs the issue.

<img width="982" alt="image" src="https://user-images.githubusercontent.com/15345355/177242616-36dce175-63b8-4544-87a5-881f602f851d.png">
<img width="982" alt="image" src="https://user-images.githubusercontent.com/15345355/177242654-42fbff6e-440d-4bb3-98bf-9eafa3f5d688.png">
